import { StyleSheet } from 'react-native';

export const commonStyles = StyleSheet.create({
  screenContainer: {
    flex: 1,
    backgroundColor: '#DEFFD0',
    padding: 16,
    justifyContent: 'center', 
    alignItems: 'center', 
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    textAlign: 'center',
    marginTop: 40,
    color: '#AD85FD',
  },
  logo: {
    width: 200, 
    height: 50, 
    marginBottom: 10,
    alignSelf: 'center',
  },
  backArrow: {
    width: 30, 
    height: 30, 
  },
  lineContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  horizontalLine: {
    height: 1,
    backgroundColor: '#AD85FD', 
    flex: 1,
  },
  circle: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#AD85FD', 
  },
  input: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 10,
    marginBottom: 16,
    fontSize: 16,
    width: '80%', 
    maxWidth: 300, 
  },
  button: {
    backgroundColor: '#AD85FD', 
    borderRadius: 8,
    width: 150,
    height: 35,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
    alignSelf: 'center',
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 20,
  },
  linkText: {
    textAlign: 'center',
    color: '#AD85FD',
    fontSize: 14,
    marginVertical: 8,
  },
  orText: {
    textAlign: 'center',
    color: 'black', 
    fontSize: 14,
    marginBottom: 5,
  },
  card: {
    width: 300, 
    height: 70,
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 16,
    marginVertical: 5,
    marginHorizontal: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    flexDirection: 'row',
    alignItems: 'center',
  },
  cardText: {
    fontSize: 16,
    color: '#333',
    marginLeft: 8,
  },
  artistText: {
    fontSize: 14,
    color: '#666',
    marginLeft: 8,
    marginTop: 4,
  },
  bottomBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 70,
    backgroundColor: '#C5C2E6',
    padding: 10,
    marginHorizontal: 25,
    marginBottom: 6,
    flexDirection: 'row',
    justifyContent: 'space-between', 
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#ddd',
    borderRadius: 25,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  bottomBarIcon: {
    marginHorizontal: 8,
    fontSize: 22,
    color: '#212121',
  },
  musicNoteIcon: {
    fontSize: 20,
    color: '#AD85FD',
    marginRight: 8,
  },
  bottomBarTrackName: {
    fontSize: 14,
    color: '#212121',
    flex: 1, 
    paddingLeft: 10, 
  },
  bottomBarControls: {
    flexDirection: 'row',
    alignItems: 'center',
  },
});